"""Edit FileUser model

Revision ID: 0d5b7544ec02
Revises: 9641a389e846
Create Date: 2024-08-26 13:39:39.089971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5b7544ec02'
down_revision: Union[str, None] = '9641a389e846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileUser', sa.Column('is_download', sa.Boolean(), nullable=False))
    op.drop_column('FileUser', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileUser', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('FileUser', 'is_download')
    # ### end Alembic commands ###
