"""Edit file model

Revision ID: f0324defe5d8
Revises: 5b43adaf2581
Create Date: 2024-08-25 01:14:49.799461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0324defe5d8'
down_revision: Union[str, None] = '5b43adaf2581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FileUser', sa.Column('url', sa.String(), nullable=False))
    op.add_column('FileUser', sa.Column('type', sa.String(), nullable=False))
    op.add_column('FileUser', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FileUser', 'size')
    op.drop_column('FileUser', 'type')
    op.drop_column('FileUser', 'url')
    # ### end Alembic commands ###
