

services:
  main_app:
    build:
      context: .

    ports:
      - 8000:8000

    volumes:
      - .:/src

    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

    env_file:
      - .env